### ISSUE TITLE
Chore: migrate from pg to postgres

### ISSUE THREAD

**Issue by clouedoc** [clouedoc/postgresql-obsidian#3]
(this might be the reason why the plugin is failing on Android)

**Comment by oliveryh** [comment]
Hi @clouedoc - I was wondering if you had any other thoughts on this? I'm looking for an obsidian plugin that allows me to connect to a database with mobile support. Is postgresql-obsidian functional on android?

**Comment by clouedoc** [comment]
Hello @oliveryh, thanks for your message.

I had technical issues while trying to implement this and gave up due to time constraints.

If I finish it, I believe the plugin would work on Android (while it currently doesn't).

I'll try to take a look today if I get the space, but you're currently in the wrong side of the time dimension, so you might want to check for other solutions 🙂

PS: why do you want a database? This plugin only sends data from your notes to Postgres. It does not allow for viewing data that is already stored.

**Comment by clouedoc** [comment]
@oliveryh so, I've tried, and it's going to be tough to implement PostgreSQL syncing with mobile. There are some APIs that are missing (`Buffer`) and I'm too lazy to try bundling this project with Browserify.

**Comment by oliveryh** [comment]
No problem. I also came to the same conclusion that attempting have full compatibility with a database on mobile was probably best avoided given the time investment. I will instead opt to use JSON. Thanks for the response!
